Integrantes
Arturo Najera Santos
Daniel Eduardo Raya Maldonado

In [ ]:
import numpy as np
from numpy import linalg as la

#Definimos las matrices del sistema
A = np.array([[0.16, 0.10],[0.17, 0.11],[2.02, 1.29]]) 
b = np.array([0.26, 0.28, 3.31])

def Givens(A):
  R=np.copy(A)
  Q=np.eye(len(A))
  for i in range(A.shape[1]): # maneja el pivote
    for j in range(i+1,len(A)):
      G=np.eye(len(R))
      ro=la.norm([R[i,i],R[j,i]])
      c=R[i,i]/ro
      s=R[j,i]/ro
      G[i,i]=c; G[i,j]=s;
      G[j,j]=c; G[j,i]=-s;
      R=G@R

      R=np.round(R,5)
      G=np.round(G,5)
      Q=Q@G.T
  return Q,R

Q,R=Givens(A)


def MinimoCuadrado(A, b):
    # Usamos Givens
    Q,R=Givens(A)


    n = A.shape[1]
    R_square = R[:n, :n]
    Qb = Q.T @ b

    # Resolvemos el sistema cuadrado
    x = np.linalg.solve(R_square, Qb[:n])
    return Q, R, x

Q, R, x = MinimoCuadrado(A, b)
Q, R, x

(array([[ 0.07868618, -0.83264764, -0.54818292],
        [ 0.08360464,  0.55346045, -0.82866773],
        [ 0.99339   ,  0.01937419,  0.11316362]]),
 array([[ 2.03345,  1.29854],
        [ 0.     ,  0.00261],
        [ 0.     , -0.     ]]),
 array([1.00021925, 0.99965559]))