In [28]:
import numpy as np  

A = np.array([[1,2,3],[4,5,6],[7,8,9]])

#Vamos a calcular la transpuesta de la matriz que es intercambiar las filas por las columnas
def Transpuesta(A):
    At = np.ones((A.shape[0], A.shape[1]))
    for fi in range(A.shape[1]):#Cambia de fila para ponerlos en la nueva columna de la nueva matriz
        c = 0 
        for co in range(A.shape[1]):#Pone a todos los elementos de la fila i como elementos columna de la nueva matriz
            #print( At[co,fi])
            #print(A.shape[1])
            c = A[fi,co]
            #print(c)
            At[co,fi] = c
            co = co + 1
    return(At)


print(Transpuesta(A))
            


[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]
